// i18n.js - OpenClaw 多语言支持
(function() {
    'use strict';

    // 语言配置
    const I18N_CONFIG = {
        defaultLang: 'zh',
        supportedLangs: ['zh', 'en'],
        storageKey: 'openclaw-language'
    };

    // 翻译数据
    const translations = {
        zh: {
            // 导航
            'nav.home': '🏠 首页',
            'nav.about': 'ℹ️ 关于',
            'nav.intro': '📖 介绍',
            'nav.install': '🚀 安装',
            'nav.feishu': '📱 飞书',
            'nav.skills': '🧩 技能',
            'nav.config': '⚙️ 配置',
            'nav.performance': '⚡ 性能',
            'nav.faq': '❓ FAQ',
            'nav.back': '← 返回首页',
            'nav.backTop': '↑ 返回顶部',
            
            // 语言切换
            'lang.switch': '🌐 语言',
            'lang.zh': '中文',
            'lang.en': 'English',
            
            // 主题切换
            'theme.light': '☀️ 浅色',
            'theme.dark': '🌙 深色',
            'theme.toggle': '切换主题',
            
            // 目录
            'toc.title': '📑 目录',
            'toc.toggle': '显示/隐藏目录',
            
            // 通用按钮
            'btn.copy': '复制',
            'btn.copied': '已复制!',
            'btn.expand': '展开',
            'btn.collapse': '收起',
            
            // 页面标题
            'title.intro': 'OpenClaw - 你的 AI 助手 | 安装、飞书接入、卸载指南',
            'title.about': '关于我们 - OpenClaw',
            'title.privacy': '隐私政策 - OpenClaw',
            
            // 页脚
            'footer.generated': 'Generated by OpenClaw 🦞',
            'footer.version': '适用版本：OpenClaw 2026.3.24+ | 最后更新：2026 年 4 月 2 日',
            'footer.security': '⚠️ 安全提示：请妥善保管 API Key、App Secret 等敏感信息，不要泄露给他人。',
            'footer.disclaimer': '免责声明：本教程仅供参考，请根据自身情况谨慎操作。因操作不当造成的损失，作者不承担责任。',
            'footer.copyright': '© 2026 OpenClaw Community. All rights reserved.',
            'footer.madeWith': 'Made with ❤️ by the OpenClaw Community',
            
            // 广告
            'ad.label': '广告',
            'ad.placeholder': '📢 广告位 - 配置 AdSense 后显示广告',
            
            // 提示框
            'tip.info': '💡 提示',
            'tip.warning': '⚠️ 警告',
            'tip.danger': '⛔ 危险',
            'tip.success': '✅ 成功',
            
            // 介绍页
            'intro.whatIs': '📖 什么是 OpenClaw？',
            'intro.description': 'OpenClaw 是一个开源的 AI 助手框架，可以运行在你自己的设备上。它不是云端服务，而是完全本地运行的智能助手。',
            'intro.updateBadge': '📝 2026.4.2 更新',
            'intro.features': '核心特点',
            'intro.feature.local': '🏠 本地运行 - 在你的电脑上运行，数据不出设备',
            'intro.feature.models': '🤖 多模型支持 - 支持 Kimi、通义千问、DeepSeek、Claude 等 30+ 模型',
            'intro.feature.channels': '💬 多渠道接入 - 支持飞书、Telegram、WhatsApp、Discord 等',
            'intro.feature.files': '📁 文件访问 - 可以读写你的工作区文件',
            'intro.feature.web': '🌐 网页浏览 - 可以搜索网络、访问网页',
            'intro.feature.cron': '⏰ 定时任务 - 支持 cron 定时任务和提醒',
            'intro.feature.memory': '🧠 记忆系统 - 长期记忆和日常笔记，保持上下文连贯',
            'intro.feature.device': '📱 设备控制 - 可连接手机/平板，查看摄像头、屏幕等',
            'intro.suitable': '💡 适合场景：',
            'intro.suitable.desc': '个人助手、自动化任务、文件处理、日程管理、信息整理、代码辅助等',
            'intro.compare': '🆚 与其他 AI 助手对比',
            'intro.quickStart': '🚀 5 分钟快速开始',
            'compare.feature': '特性',
            'compare.wenxin': '文心一言',
            
            // 安装页
            'install.title': '🚀 安装与配置',
            'install.prerequisites': '⚙️ 前置条件',
            'install.prerequisites.warning': '⚠️ 安装前请确保满足以下所有要求：',
            'install.methods': '📦 安装方法',
            'install.npm': 'npm 安装',
            'install.source': '源码安装',
            'install.docker': 'Docker',
            'install.init': '🎯 初始化与配置',
            'install.verify': '✅ 验证运行',
            
            // 飞书页
            'feishu.title': '📱 接入飞书',
            'feishu.version': '⚠️ 版本要求：OpenClaw v2026.2.26+ | 需要飞书企业账号和开放平台管理员权限',
            'feishu.prerequisites': '📋 前置条件',
            'feishu.createApp': '🔧 飞书应用创建',
            'feishu.permissions': '🔐 应用权限配置',
            'feishu.events': '📡 事件订阅',
            'feishu.config': '⚙️ OpenClaw 端配置',
            'feishu.publish': '🚀 发布与测试',
            
            // 技能页
            'skills.title': '🧩 技能扩展',
            'skills.description': 'OpenClaw 支持通过 ClawHub 安装额外技能，扩展 AI 助手的能力边界。',
            'skills.market': '🌐 技能市场：',
            'skills.popular': '📦 热门技能推荐',
            'skills.fileManager': '📁 文件管理',
            'skills.webBrowse': '🌐 网页浏览',
            'skills.calendar': '📅 日历/邮件',
            'skills.custom': '🛠️ 自定义技能',
            'skills.commands': '🔧 技能管理命令',
            
            // 性能页
            'performance.title': '⚡ 性能优化指南',
            'performance.modelSelect': '📊 模型选择建议',
            'performance.config': '🔧 配置优化',
            'performance.maintenance': '🧹 定期维护',
            
            // FAQ页
            'faq.title': '❓ 常见问题',
            'faq.moreHelp': '📞 获取帮助',
            'faq.security': '🔒 安全最佳实践',
            
            // 卸载页
            'uninstall.title': '🗑️ 删除/卸载',
            'uninstall.warning': '⚠️ 警告：卸载将删除所有配置、记忆和聊天记录！请提前备份重要数据。',
            'uninstall.standard': '📌 标准卸载流程（CLI 可用时）',
            'uninstall.manual': '🔧 手动卸载步骤（CLI 不可用时）',
            'uninstall.cleanup': '🧹 彻底清理',
            'uninstall.security': '🔒 安全提醒',
            
            // 资源页
            'resources.title': '🔗 资源与社区',
            'resources.official': '📖 官方资源',
            'resources.community': '💬 社区交流',
            'resources.tutorials': '📚 相关教程',
            'resources.contribute': '🤝 贡献与支持',
            
            // 关于页
            'about.mission': '🚀 我们的使命',
            'about.mission.text': 'OpenClaw 是一个开源的 AI 助手框架项目，诞生于 2024 年。我们的目标很简单：让每个人都能在自己的设备上运行 AI 助手，无需依赖云端服务，保护个人隐私。',
            'about.why': '💡 为什么创建 OpenClaw？',
            'about.why.text': '我们相信 AI 应该是每个人的工具，而不是少数公司的专利。通过开源和本地运行，我们让用户完全掌控自己的数据和 AI 体验。',
            'about.values.core': '核心理念',
            'about.values.privacy': '🔒 隐私优先 - 数据存储在本地，不上传到我们的服务器',
            'about.values.opensource': '🌍 开源透明 - 代码完全开源，接受社区监督',
            'about.values.community': '🤝 社区驱动 - 由全球贡献者共同维护和发展',
            'about.values.free': '💰 免费使用 - 软件本身免费，只需支付 AI 模型 API 费用',
            'about.values.customizable': '🔧 高度可定制 - 支持自定义技能、多渠道接入',
            'about.history': '📅 项目历程',
            'about.team': '👥 团队介绍',
            'about.join': '🤝 加入我们！',
            'about.values': '💎 我们的价值观',
            'about.stats': '📊 项目统计',
            'about.partners': '🤝 合作伙伴',
            'about.contact': '📬 联系我们',
            
            // 隐私页
            'privacy.intro': '1. 引言',
            'privacy.collection': '2. 信息收集',
            'privacy.use': '3. 信息使用',
            'privacy.cookies': '4. Cookie 和追踪技术',
            'privacy.thirdParty': '5. 第三方服务',
            'privacy.security': '6. 数据安全',
            'privacy.rights': '7. 您的权利',
            'privacy.children': '8. 儿童隐私',
            'privacy.changes': '9. 政策变更',
            'privacy.contact': '10. 联系我们',
            'privacy.lastUpdated': '📅 最后更新：2026 年 4 月 2 日',
            
            // 新增 - 介绍页详细内容
            'intro.privacyFirst': '🔒 隐私优先',
            'intro.privacyFirst.desc': '所有对话、文件、记忆都保存在你的设备上',
            'intro.modelFreedom': '🤖 模型自由',
            'intro.modelFreedom.desc': '不被锁定在单一 AI 提供商，随时切换',
            'intro.localFirst': '⚡ 本地优先',
            'intro.localFirst.desc': '支持 Ollama 本地模型，无需联网也能使用',
            'intro.customizable': '🔧 高度可定制',
            'intro.customizable.desc': '通过技能系统扩展能力，打造专属助手',
            'intro.costControl': '💰 成本可控',
            'intro.costControl.desc': '开源免费，按需使用 API，无订阅费',
            'intro.coreIdea': '🎯 核心理念',
            'intro.coreIdea.desc': 'AI 助手应该是你的私人工具，而不是将你数据上传云端的服务。',
            'intro.whyChoose': '为什么选择 OpenClaw？',
            'intro.scenarios': '🎯 10 个实际应用场景',
            'intro.scenario1.title': '1. 个人知识管理 📚',
            'intro.scenario1.desc': '整理笔记、提取重点、建立知识库，让 AI 帮你记住一切重要信息。',
            'intro.scenario2.title': '2. 代码开发助手 💻',
            'intro.scenario2.desc': '代码补全、Bug 排查、代码审查、技术文档生成，提升 2-3 倍开发效率。',
            'intro.scenario3.title': '3. 内容创作 ✍️',
            'intro.scenario3.desc': '文章写作、文案润色、翻译校对、创意头脑风暴，激发无限灵感。',
            'intro.scenario4.title': '4. 数据分析 📊',
            'intro.scenario4.desc': 'CSV 处理、数据清洗、可视化建议、报告生成，让数据说话。',
            'intro.scenario5.title': '5. 自动化工作流 🤖',
            'intro.scenario5.desc': '定时任务、文件监控、API 调用、多步骤自动化，告别重复劳动。',
            'intro.scenario6.title': '6. 学习辅导 📖',
            'intro.scenario6.desc': '外语练习、概念解释、习题解答、学习计划制定，你的私人教师。',
            'intro.scenario7.title': '7. 生活助手 🏠',
            'intro.scenario7.desc': '菜谱推荐、旅行规划、日程提醒、健康管理，让生活更有序。',
            'intro.scenario8.title': '8. 企业协作 👥',
            'intro.scenario8.desc': '飞书/Telegram 机器人、团队知识库、会议纪要、项目管理。',
            'intro.scenario9.title': '9. 研究与调研 🔬',
            'intro.scenario9.desc': '文献综述、竞品分析、市场调研、信息聚合，快速获取洞察。',
            'intro.scenario10.title': '10. 创意娱乐 🎨',
            'intro.scenario10.desc': '故事创作、游戏设计、角色扮演、趣味对话，释放创造力。',
            'intro.architecture': '🏗️ 技术架构概览',
            'intro.architecture.desc': 'OpenClaw 采用模块化架构设计，核心组件包括：',
            'intro.arch.gateway': 'Gateway',
            'intro.arch.gateway.desc': 'HTTP 服务器，处理所有请求和会话管理',
            'intro.arch.agent': 'Agent Runtime',
            'intro.arch.agent.desc': 'AI 模型调用和工具执行引擎',
            'intro.arch.skill': 'Skill System',
            'intro.arch.skill.desc': '可插拔的技能扩展机制',
            'intro.arch.memory': 'Memory Layer',
            'intro.arch.memory.desc': '长期记忆和上下文管理',
            'intro.arch.channel': 'Channel Adapters',
            'intro.arch.channel.desc': '多渠道接入适配器（飞书、Telegram 等）',
            'intro.arch.cron': 'Cron Scheduler',
            'intro.arch.cron.desc': '定时任务调度器',
            'intro.community': '🎉 社区生态',
            'intro.community.desc': 'OpenClaw 拥有活跃的开发者社区，持续贡献技能、插件和改进：',
            'intro.community.skills': '🌟 100+ 社区技能',
            'intro.community.skills.desc': '从网页爬虫到数据库管理，应有尽有',
            'intro.community.channels': '📦 30+ 集成渠道',
            'intro.community.channels.desc': '支持主流通讯工具和平台',
            'intro.community.updates': '🔥 每周更新',
            'intro.community.updates.desc': '快速迭代，持续优化',
            'intro.community.languages': '🌍 多语言支持',
            'intro.community.languages.desc': '中文、英文、日文等',
            'intro.community.opensource': '🤝 开源协作',
            'intro.community.opensource.desc': 'GitHub 上活跃的 Issue 和 PR 讨论',
            'intro.ready': '🚀 准备好开始了吗？',
            'intro.ready.desc': '继续阅读下方的安装与配置章节，或加入 Discord 社区获取帮助！',
            
            // 安装页面详细内容
            'install.step1': '步骤 1：安装 Node.js',
            'install.step2': '步骤 2：安装 OpenClaw',
            'install.step3': '步骤 3：运行向导',
            'install.step4': '步骤 4：开始对话',
            'install.step5': '步骤 5',
            'install.nodejs': '安装 Node.js',
            'install.nodejs.desc': '访问 nodejs.org 下载并安装 v22+ 版本。',
            'install.openclaw': '安装 OpenClaw',
            'install.wizard': '运行向导',
            'install.wizard.desc': '按提示选择 AI 模型（推荐 Kimi 或 DeepSeek）并完成配置。',
            'install.startChat': '开始对话',
            'install.startChat.desc': '或打开浏览器访问 http://localhost:18789',
            'install.complete': '✅ 完成！你现在拥有了一个运行在自己设备上的 AI 助手。',
            'install.prerequisites': '前置条件',
            'install.prerequisites.warning': '⚠️ 安装前请确保满足以下所有要求：',
            'install.os': '操作系统',
            'install.os.desc': 'Windows 10+ / macOS 11+ / Linux (Ubuntu 20.04+)',
            'install.node': 'Node.js',
            'install.node.desc': '≥ 22.0.0 (必须)',
            'install.npm': 'npm',
            'install.npm.desc': '≥ 10.0.0 (随 Node.js 安装)',
            'install.git': 'Git',
            'install.git.desc': '用于版本控制和技能管理',
            'install.memory': '内存',
            'install.memory.desc': '至少 2GB 可用内存',
            'install.memory.check': '任务管理器查看',
            'install.disk': '磁盘空间',
            'install.disk.desc': '至少 500MB 可用空间',
            'install.network': '网络',
            'install.network.desc': '需要访问 AI 模型 API（可能需要代理）',
            'install.network.check': '确保能访问外网',
            'install.requirement': '要求',
            'install.details': '详细说明',
            'install.verifyCmd': '验证命令',
            'install.cloudModels': '云端模型',
            'install.localModels': '本地模型',
            'install.configFormat': '配置文件格式',
            'install.deepseek': 'DeepSeek 配置',
            'install.deepseek.key': '获取 API Key',
            'install.kimi': 'Kimi (Moonshot) 配置',
            'install.qwen': '通义千问 (Qwen) 配置',
            'install.ollama': 'Ollama + Qwen 配置',
            'install.otherLocal': '其他本地模型',
            
            // 安装步骤详细内容
            'install.step1.title': '步骤 1：安装 Node.js',
            'install.step1.windows': 'Windows：访问 nodejs.org 下载 .msi 安装程序',
            'install.step1.macos': 'macOS：',
            'install.step1.linux': 'Linux：',
            'install.step2.title': '步骤 2：全局安装 OpenClaw',
            'install.step3.title': '步骤 3：验证安装',
            'install.step3.desc': '应输出版本号，如：2026.3.24',
            'install.source.step1': '步骤 1：克隆仓库',
            'install.source.step2': '步骤 2：安装依赖并链接',
            'install.docker.step1': '步骤 1：拉取镜像',
            'install.docker.step2': '步骤 2：运行容器',
            'install.wizard.title': '运行交互式向导',
            'install.wizard.desc2': '交互式向导将引导你完成以下配置：',
            'install.wizard.provider': '选择 AI 模型提供商',
            'install.wizard.provider.desc': 'Kimi、DeepSeek、通义千问、Ollama 等',
            'install.wizard.auth': '配置认证信息',
            'install.wizard.auth.desc': 'API 密钥或 OAuth 授权',
            'install.wizard.workspace': '设置工作区目录',
            'install.wizard.workspace.desc': '默认 ~/.openclaw/workspace',
            'install.wizard.channels': '配置渠道',
            'install.wizard.channels.desc': '飞书、Telegram、WhatsApp 等（可选）',
            'install.wizard.daemon': '安装守护进程',
            'install.wizard.daemon.desc': '开机自启动（可选）',
            'install.wizard.configLocation': '配置文件位置',
            'install.wizard.configLocation.win': 'Windows',
            'install.wizard.configLocation.unix': 'macOS/Linux',
            
            // AI 模型配置
            'config.ai.title': '🤖 AI 模型配置',
            'config.ai.cloud': '云端模型',
            'config.ai.cloud.desc': '云端模型无需本地 GPU，通过 API 调用，适合大多数用户',
            'config.ai.local': '本地模型',
            'config.ai.local.desc': '本地模型需要 GPU（建议 8GB+ 显存），数据完全本地，适合隐私敏感场景',
            'config.ai.configFormat': '配置文件格式',
            'config.ai.configFormat.desc': 'OpenClaw 支持多种配置文件格式，根据需求选择',
            
            // 模型配置详情
            'model.deepseek.title': 'DeepSeek 配置',
            'model.deepseek.getKey': '获取 API Key',
            'model.deepseek.visit': '访问',
            'model.kimi.title': 'Kimi (Moonshot) 配置',
            'model.kimi.getKey': '获取 API Key',
            'model.qwen.title': '通义千问 (Qwen) 配置',
            'model.qwen.getKey': '获取 API Key',
            'model.qwen.oauth': '通义千问支持 OAuth 登录，运行',
            'model.qwen.oauth.cmd': '授权',
            
            // Ollama 配置
            'model.ollama.install': '1. 安装 Ollama',
            'model.ollama.pull': '2. 拉取模型',
            'model.ollama.qwen7b': 'Qwen2.5 7B (约需 4GB 显存)',
            'model.ollama.qwen14b': 'Qwen2.5 14B (约需 8GB 显存)',
            'model.ollama.list': '查看已下载模型',
            'model.ollama.verify': '3. 验证 Ollama 运行',
            'model.ollama.config': '4. OpenClaw 配置',
            'model.ollama.start': '5. 启动并测试',
            
            // 其他本地模型
            'model.other.llama': 'Llama 3.2',
            'model.other.mistral': 'Mistral',
            'model.other.phi': 'Phi-3',
            
            // 配置文件
            'config.file.main': 'openclaw.json（主配置文件）',
            'config.file.main.desc': '这是 OpenClaw 的主要配置文件，位于',
            'config.file.env': '.env（环境变量）',
            'config.file.env.desc': '用于存储敏感信息如 API 密钥，不会被提交到版本控制',
            'config.file.agents': 'AGENTS.md（智能体配置）',
            'config.file.agents.desc': '定义 AI 智能体的行为、角色和系统提示词',
            
            // 安装向导步骤
            'install.wizard.step1': '设置 AI 模型提供商',
            'install.wizard.step1.desc': '选择 Kimi、DeepSeek、通义千问等',
            'install.wizard.step2': '配置 API Key',
            'install.wizard.step2.desc': '输入从模型提供商获取的密钥',
            'install.wizard.step3': '设置工作区目录',
            'install.wizard.step3.desc': '默认 ~/.openclaw/workspace',
            'install.wizard.step4': '配置渠道',
            'install.wizard.step4.desc': '飞书、Telegram、WhatsApp 等（可选）',
            'install.wizard.step5': '安装守护进程',
            'install.wizard.step5.desc': '开机自启动（可选）',
            'install.wizard.tip': '提示：',
            'install.wizard.tip.desc': '配置完成后会在 ~/.openclaw/ 目录生成配置文件',
            
            // 对比表格
            'compare.privacy': '数据隐私',
            'compare.privacy.local': '✅ 完全本地',
            'compare.privacy.cloud': '❌ 云端存储',
            'compare.models': '模型选择',
            'compare.models.multi': '✅ 30+ 模型',
            'compare.models.single': '⚠️ 单一厂商',
            'compare.fileAccess': '文件访问',
            'compare.fileAccess.direct': '✅ 直接读写',
            'compare.fileAccess.upload': '❌ 需手动上传',
            'compare.localDeploy': '本地部署',
            'compare.localDeploy.support': '✅ 支持 Ollama',
            'compare.localDeploy.nosupport': '❌ 不支持',
            'compare.cron': '定时任务',
            'compare.cron.builtin': '✅ 内置 cron',
            'compare.cron.none': '❌ 不支持',
            'compare.memory': '记忆系统',
            'compare.memory.longterm': '✅ 长期记忆',
            'compare.memory.session': '⚠️ 会话内',
            'compare.opensource': '开源',
            'compare.opensource.yes': '✅ 完全开源',
            'compare.opensource.no': '❌ 闭源',
            'compare.customSkills': '自定义技能',
            'compare.customSkills.yes': '✅ 支持',
            'compare.customSkills.no': '❌ 不支持',
            'compare.cost': '成本',
            'compare.cost.free': '💰 免费 + API 费用',
            'compare.cost.subscription': '💰💰 订阅制',
            
            // 平台名称
            'platform.windows': 'Windows',
            'platform.macos': 'macOS',
            'platform.linux': 'Linux',
            
            // 错误消息
            'error.generic': '发生错误',
            'error.notFound': '未找到',
            'error.invalidInput': '输入无效',
            'error.network': '网络错误',
            'error.timeout': '请求超时',
            'error.unauthorized': '未授权',
            'error.forbidden': '禁止访问',
            'error.server': '服务器错误',
            'error.unknown': '未知错误',
            'error.config': '配置错误',
            'error.fileNotFound': '文件未找到',
            'error.permissionDenied': '权限被拒绝',
            'error.diskFull': '磁盘空间不足',
            'error.alreadyExists': '已存在',
            'error.notSupported': '不支持的操作',
            
            // 提示消息
            'msg.welcome': '欢迎使用 OpenClaw！',
            'msg.setupComplete': '设置完成！',
            'msg.configSaved': '配置已保存',
            'msg.changesSaved': '更改已保存',
            'msg.fileSaved': '文件已保存',
            'msg.fileDeleted': '文件已删除',
            'msg.skillInstalled': '技能已安装',
            'msg.skillUpdated': '技能已更新',
            'msg.skillRemoved': '技能已移除',
            'msg.channelConnected': '渠道已连接',
            'msg.channelDisconnected': '渠道已断开',
            'msg.modelChanged': '模型已切换',
            'msg.languageChanged': '语言已切换',
            'msg.themeChanged': '主题已切换',
            'msg.noResults': '无结果',
            'msg.loading': '加载中...',
            'msg.pleaseWait': '请稍候...',
            'msg.comingSoon': '即将推出',
            'msg.workInProgress': '开发中...',
            
            // AI 模型相关
            'model.provider': '模型提供商',
            'model.name': '模型名称',
            'model.version': '模型版本',
            'model.type': '模型类型',
            'model.cloud': '云端模型',
            'model.local': '本地模型',
            'model.apiKey': 'API 密钥',
            'model.baseUrl': '基础 URL',
            'model.temperature': '温度参数',
            'model.maxTokens': '最大令牌数',
            'model.timeout': '超时时间',
            'model.retry': '重试次数',
            'model.fallback': '备用模型',
            
            // 模型提供商名称
            'model.openai': 'OpenAI',
            'model.anthropic': 'Anthropic',
            'model.google': 'Google',
            'model.moonshot': 'Moonshot (Kimi)',
            'model.deepseek': 'DeepSeek',
            'model.alibaba': 'Alibaba (Qwen)',
            'model.ollama': 'Ollama',
            'model.siliconflow': 'SiliconFlow',
            
            // 配置相关
            'config.file': '配置文件',
            'config.path': '配置路径',
            'config.edit': '编辑配置',
            'config.reset': '重置配置',
            'config.backup': '备份配置',
            'config.restore': '恢复配置',
            'config.import': '导入配置',
            'config.export': '导出配置',
            'config.validate': '验证配置',
            'config.reload': '重新加载',
            
            // 技能相关
            'skill.name': '技能名称',
            'skill.description': '技能描述',
            'skill.version': '版本',
            'skill.author': '作者',
            'skill.license': '许可证',
            'skill.repository': '代码仓库',
            'skill.documentation': '文档',
            'skill.install': '安装技能',
            'skill.uninstall': '卸载技能',
            'skill.update': '更新技能',
            'skill.enable': '启用技能',
            'skill.disable': '禁用技能',
            'skill.configure': '配置技能',
            'skill.market': '技能市场',
            'skill.installed': '已安装技能',
            'skill.available': '可用技能',
            'skill.popular': '热门技能',
            'skill.new': '最新技能',
            'skill.search': '搜索技能',
            'skill.category': '技能分类',
            
            // 渠道相关
            'channel.name': '渠道名称',
            'channel.type': '渠道类型',
            'channel.status': '渠道状态',
            'channel.configure': '配置渠道',
            'channel.enable': '启用渠道',
            'channel.disable': '禁用渠道',
            'channel.test': '测试渠道',
            'channel.webchat': 'Web 聊天',
            'channel.telegram': 'Telegram',
            'channel.discord': 'Discord',
            'channel.feishu': '飞书',
            'channel.whatsapp': 'WhatsApp',
            'channel.slack': 'Slack',
            'channel.wechat': '微信',
            
            // 飞书页面详细内容
            'feishu.pairing': '🔗 配对流程（可选）',
            'feishu.pairing.desc': '如需将飞书与 OpenClaw 深度集成，可使用配对功能：',
            
            // 技能页面详细内容
            'skills.fileManager.desc': '让 AI 助手可以读写、整理、搜索你的文件。',
            'skills.fileManager.features': '功能：',
            'skills.fileManager.useCases': '适用场景：',
            'skills.webBrowse.desc': '让 AI 助手可以访问网页、搜索信息、抓取内容。',
            'skills.calendar.desc': '连接你的日历和邮箱，实现智能日程管理和邮件处理。',
            'skills.custom.desc': '创建属于你自己的技能，满足特定需求。',
            
            // 卸载页面详细内容
            'uninstall.interactive': '交互式卸载',
            'uninstall.auto': '自动卸载',
            'uninstall.windows': 'Windows',
            'uninstall.macos': 'macOS',
            'uninstall.linux': 'Linux',
            
            // 通用命令和状态
            'cmd.install': '安装',
            'cmd.install.global': '全局安装',
            'cmd.uninstall': '卸载',
            'cmd.update': '更新',
            'cmd.start': '启动',
            'cmd.stop': '停止',
            'cmd.restart': '重启',
            'cmd.status': '查看状态',
            'cmd.config': '配置',
            'cmd.chat': '对话',
            'cmd.help': '帮助',
            'cmd.version': '版本',
            
            // 状态消息
            'status.success': '成功',
            'status.error': '错误',
            'status.warning': '警告',
            'status.info': '信息',
            'status.loading': '加载中...',
            'status.done': '完成',
            'status.pending': '待处理',
            
            // 操作按钮
            'action.confirm': '确认',
            'action.cancel': '取消',
            'action.save': '保存',
            'action.delete': '删除',
            'action.edit': '编辑',
            'action.add': '添加',
            'action.remove': '移除',
            'action.search': '搜索',
            'action.filter': '筛选',
            'action.refresh': '刷新',
            'action.download': '下载',
            'action.upload': '上传',
            'action.share': '分享',
            'action.copy': '复制',
            'action.paste': '粘贴',
            'action.cut': '剪切',
            'action.selectAll': '全选',
            'action.undo': '撤销',
            'action.redo': '重做',
            
            // 表单标签
            'form.name': '名称',
            'form.description': '描述',
            'form.email': '邮箱',
            'form.password': '密码',
            'form.confirmPassword': '确认密码',
            'form.url': '网址',
            'form.token': '令牌',
            'form.key': '密钥',
            'form.value': '值',
            'form.type': '类型',
            'form.category': '分类',
            'form.tag': '标签',
            'form.status': '状态',
            'form.required': '必填',
            'form.optional': '可选',
            'form.default': '默认',
            'form.custom': '自定义',
            
            // 时间相关
            'time.now': '现在',
            'time.today': '今天',
            'time.yesterday': '昨天',
            'time.tomorrow': '明天',
            'time.thisWeek': '本周',
            'time.lastWeek': '上周',
            'time.thisMonth': '本月',
            'time.lastMonth': '上月',
            'time.recent': '最近',
            'time.justNow': '刚刚',
            'time.minutesAgo': '分钟前',
            'time.hoursAgo': '小时前',
            'time.daysAgo': '天前',
            
            // 文件相关
            'file.name': '文件名',
            'file.size': '大小',
            'file.type': '类型',
            'file.path': '路径',
            'file.folder': '文件夹',
            'file.document': '文档',
            'file.image': '图片',
            'file.video': '视频',
            'file.audio': '音频',
            'file.archive': '压缩包',
            'file.code': '代码文件',
            'file.new': '新建文件',
            'file.open': '打开文件',
            'file.save': '保存文件',
            'file.saveAs': '另存为',
            'file.rename': '重命名',
            'file.delete': '删除文件',
            'file.move': '移动',
            'file.copy': '复制',
            'file.duplicate': '创建副本',
            
            // 资源页面详细内容
            'resources.docs': '官方文档',
            'resources.docs.desc': '完整使用指南',
            'resources.github': 'GitHub 仓库',
            'resources.github.desc': '源码与 Issue 追踪',
            'resources.clawhub': '技能市场',
            'resources.clawhub.desc': '发现和分享技能',
            'resources.releases': '更新日志',
            'resources.releases.desc': '版本更新记录',
            'resources.discord': 'Discord 社区',
            'resources.discord.desc': '实时交流与答疑',
            'resources.telegram': 'Telegram 群组',
            'resources.telegram.desc': '中文讨论',
            'resources.twitter': 'Twitter/X',
            'resources.twitter.desc': '官方动态',
            'resources.gettingStarted': '新手入门指南',
            'resources.gettingStarted.desc': '从零开始使用 OpenClaw',
            'resources.skillDev': '技能开发教程',
            'resources.skillDev.desc': '创建自定义技能',
            'resources.feishuGuide': '飞书接入详解',
            'resources.feishuGuide.desc': '深度配置指南',
            'resources.automation': '自动化工作流',
            'resources.automation.desc': '定时任务与自动化',
            'resources.bugReport': '提交 Bug',
            'resources.featureRequest': '功能建议',
            'resources.submitSkill': '提交技能',
            'resources.sponsor': '赞助项目'
        },
        en: {
            // Navigation
            'nav.home': '🏠 Home',
            'nav.about': 'ℹ️ About',
            'nav.intro': '📖 Intro',
            'nav.install': '🚀 Install',
            'nav.feishu': '📱 Feishu',
            'nav.skills': '🧩 Skills',
            'nav.config': '⚙️ Config',
            'nav.performance': '⚡ Performance',
            'nav.faq': '❓ FAQ',
            'nav.back': '← Back to Home',
            'nav.backTop': '↑ Back to Top',
            
            // Language switch
            'lang.switch': '🌐 Language',
            'lang.zh': '中文',
            'lang.en': 'English',
            
            // Theme
            'theme.light': '☀️ Light',
            'theme.dark': '🌙 Dark',
            'theme.toggle': 'Toggle Theme',
            
            // TOC
            'toc.title': '📑 Contents',
            'toc.toggle': 'Show/Hide Contents',
            
            // Buttons
            'btn.copy': 'Copy',
            'btn.copied': 'Copied!',
            'btn.expand': 'Expand',
            'btn.collapse': 'Collapse',
            
            // Page titles
            'title.intro': 'OpenClaw - Your AI Assistant | Installation, Feishu Integration, Uninstall Guide',
            'title.about': 'About Us - OpenClaw',
            'title.privacy': 'Privacy Policy - OpenClaw',
            
            // Footer
            'footer.generated': 'Generated by OpenClaw 🦞',
            'footer.version': 'Applicable Version: OpenClaw 2026.3.24+ | Last Updated: April 2, 2026',
            'footer.security': '⚠️ Security Tip: Please keep your API Keys, App Secrets and other sensitive information secure. Do not share them with others.',
            'footer.disclaimer': 'Disclaimer: This tutorial is for reference only. Please proceed with caution based on your own situation. The author is not responsible for any losses caused by improper operation.',
            'footer.copyright': '© 2026 OpenClaw Community. All rights reserved.',
            'footer.madeWith': 'Made with ❤️ by the OpenClaw Community',
            
            // Ads
            'ad.label': 'ADVERTISEMENT',
            'ad.placeholder': '📢 Ad Space - Configure AdSense to display ads',
            
            // Tips
            'tip.info': '💡 Tip',
            'tip.warning': '⚠️ Warning',
            'tip.danger': '⛔ Danger',
            'tip.success': '✅ Success',
            
            // Intro page
            'intro.whatIs': '📖 What is OpenClaw?',
            'intro.whatIs.desc': 'OpenClaw is an',
            'intro.whatIs.mid': 'AI assistant framework that runs on your own device. Unlike cloud services like ChatGPT and Claude, OpenClaw keeps all data locally, giving you true',
            'intro.whatIs.em': 'data sovereignty',
            'intro.whatIs.end': '.',
            'intro.description': 'OpenClaw is an open-source AI assistant framework that runs on your own device. It is not a cloud service, but a completely locally-run intelligent assistant.', 
            'intro.updateBadge': '📝 Updated 2026.4.2',
            'intro.features': 'Key Features',
            'intro.feature.local': '🏠 Local Execution - Runs on your computer, data never leaves your device',
            'intro.feature.models': '🤖 Multi-Model Support - Supports 30+ models including Kimi, Qwen, DeepSeek, Claude',
            'intro.feature.channels': '💬 Multi-Channel Integration - Supports Feishu, Telegram, WhatsApp, Discord, etc.',
            'intro.feature.files': '📁 File Access - Read and write files in your workspace',
            'intro.feature.web': '🌐 Web Browsing - Search the web and access websites',
            'intro.feature.cron': '⏰ Scheduled Tasks - Supports cron jobs and reminders',
            'intro.feature.memory': '🧠 Memory System - Long-term memory and daily notes for context continuity',
            'intro.feature.device': '📱 Device Control - Connect to phones/tablets, view camera, screen, etc.',
            'intro.suitable': '💡 Suitable for:',
            'intro.suitable.desc': 'Personal assistant, automation tasks, file processing, schedule management, information organization, code assistance, etc.',
            'intro.compare': '🆚 Comparison with Other AI Assistants',
            'intro.quickStart': '🚀 5-Minute Quick Start',
            'compare.feature': 'Feature',
            'compare.wenxin': 'Wenxin Yiyan',
            
            // Install page
            'install.title': '🚀 Installation & Configuration',
            'install.prerequisites': '⚙️ Prerequisites',
            'install.prerequisites.warning': '⚠️ Please ensure all requirements are met before installation:',
            'install.methods': '📦 Installation Methods',
            'install.npm': 'npm Install',
            'install.source': 'Source Install',
            'install.docker': 'Docker',
            'install.init': '🎯 Initialization & Configuration',
            'install.verify': '✅ Verify Installation',
            
            // Feishu page
            'feishu.title': '📱 Feishu Integration',
            'feishu.version': '⚠️ Version Requirements: OpenClaw v2026.2.26+ | Requires Feishu Enterprise account and Open Platform admin permissions',
            'feishu.prerequisites': '📋 Prerequisites',
            'feishu.createApp': '🔧 Create Feishu App',
            'feishu.permissions': '🔐 App Permissions',
            'feishu.events': '📡 Event Subscriptions',
            'feishu.config': '⚙️ OpenClaw Configuration',
            'feishu.publish': '🚀 Publish & Test',
            
            // Skills page
            'skills.title': '🧩 Skills Extension',
            'skills.description': 'OpenClaw supports installing additional skills via ClawHub to extend your AI assistant\'s capabilities.',
            'skills.market': '🌐 Skills Marketplace:',
            'skills.popular': '📦 Popular Skills',
            'skills.fileManager': '📁 File Manager',
            'skills.webBrowse': '🌐 Web Browse',
            'skills.calendar': '📅 Calendar/Email',
            'skills.custom': '🛠️ Custom Skills',
            'skills.commands': '🔧 Skill Management Commands',
            
            // Performance page
            'performance.title': '⚡ Performance Optimization Guide',
            'performance.modelSelect': '📊 Model Selection Recommendations',
            'performance.config': '🔧 Configuration Optimization',
            'performance.maintenance': '🧹 Regular Maintenance',
            
            // FAQ page
            'faq.title': '❓ Frequently Asked Questions',
            'faq.moreHelp': '📞 Get Help',
            'faq.security': '🔒 Security Best Practices',
            
            // Uninstall page
            'uninstall.title': '🗑️ Uninstall',
            'uninstall.warning': '⚠️ Warning: Uninstalling will delete all configurations, memories, and chat history! Please backup important data first.',
            'uninstall.standard': '📌 Standard Uninstall (when CLI is available)',
            'uninstall.manual': '🔧 Manual Uninstall (when CLI is unavailable)',
            'uninstall.cleanup': '🧹 Complete Cleanup',
            'uninstall.security': '🔒 Security Reminder',
            
            // Resources page
            'resources.title': '🔗 Resources & Community',
            'resources.official': '📖 Official Resources',
            'resources.community': '💬 Community',
            'resources.tutorials': '📚 Tutorials',
            'resources.contribute': '🤝 Contribute & Support',
            
            // About page
            'about.mission': '🚀 Our Mission',
            'about.mission.text': 'OpenClaw is an open-source AI assistant framework project, born in 2024. Our goal is simple: let everyone run AI assistants on their own devices, without relying on cloud services, protecting personal privacy.',
            'about.why': '💡 Why Create OpenClaw?',
            'about.why.text': 'We believe AI should be a tool for everyone, not just a few companies. Through open source and local execution, we give users complete control over their data and AI experience.',
            'about.values.core': 'Core Values',
            'about.values.privacy': '🔒 Privacy First - Data is stored locally, not uploaded to our servers',
            'about.values.opensource': '🌍 Open Source - Code is fully open source, subject to community oversight',
            'about.values.community': '🤝 Community Driven - Maintained and developed by global contributors',
            'about.values.free': '💰 Free to Use - Software is free, only pay for AI model API usage',
            'about.values.customizable': '🔧 Highly Customizable - Supports custom skills, multi-channel integration',
            'about.history': '📅 Project History',
            'about.team': '👥 Our Team',
            'about.join': '🤝 Join Us!',
            'about.values': '💎 Our Values',
            'about.stats': '📊 Project Statistics',
            'about.partners': '🤝 Partners',
            'about.contact': '📬 Contact Us',
            
            // Privacy page
            'privacy.intro': '1. Introduction',
            'privacy.collection': '2. Information Collection',
            'privacy.use': '3. Information Use',
            'privacy.cookies': '4. Cookies & Tracking',
            'privacy.thirdParty': '5. Third-Party Services',
            'privacy.security': '6. Data Security',
            'privacy.rights': '7. Your Rights',
            'privacy.children': '8. Children\'s Privacy',
            'privacy.changes': '9. Policy Changes',
            'privacy.contact': '10. Contact Us',
            'privacy.lastUpdated': '📅 Last Updated: April 2, 2026',
            
            // New - Intro page detailed content
            'intro.privacyFirst': '🔒 Privacy First',
            'intro.privacyFirst.desc': 'All conversations, files, and memories are stored on your device',
            'intro.modelFreedom': '🤖 Model Freedom',
            'intro.modelFreedom.desc': 'Not locked into a single AI provider, switch anytime',
            'intro.localFirst': '⚡ Local First',
            'intro.localFirst.desc': 'Supports Ollama local models, works offline without internet',
            'intro.customizable': '🔧 Highly Customizable',
            'intro.customizable.desc': 'Extend capabilities through skill system, build your own assistant',
            'intro.costControl': '💰 Cost Control',
            'intro.costControl.desc': 'Open source and free, pay only for API usage, no subscription fees',
            'intro.coreIdea': '🎯 Core Philosophy',
            'intro.coreIdea.desc': 'AI assistants should be your private tools, not services that upload your data to the cloud.',
            'intro.whyChoose': 'Why Choose OpenClaw?',
            'intro.scenarios': '🎯 10 Real-World Use Cases',
            'intro.scenario1.title': '1. Personal Knowledge Management 📚',
            'intro.scenario1.desc': 'Organize notes, extract key points, build knowledge bases - let AI remember everything important.',
            'intro.scenario2.title': '2. Code Development Assistant 💻',
            'intro.scenario2.desc': 'Code completion, bug fixing, code review, technical documentation - boost productivity by 2-3x.',
            'intro.scenario3.title': '3. Content Creation ✍️',
            'intro.scenario3.desc': 'Article writing, copy editing, translation, creative brainstorming - unlock unlimited inspiration.',
            'intro.scenario4.title': '4. Data Analysis 📊',
            'intro.scenario4.desc': 'CSV processing, data cleaning, visualization suggestions, report generation - make data speak.',
            'intro.scenario5.title': '5. Automation Workflows 🤖',
            'intro.scenario5.desc': 'Scheduled tasks, file monitoring, API calls, multi-step automation - say goodbye to repetitive work.',
            'intro.scenario6.title': '6. Learning & Tutoring 📖',
            'intro.scenario6.desc': 'Language practice, concept explanations, exercise solutions, study planning - your private tutor.',
            'intro.scenario7.title': '7. Life Assistant 🏠',
            'intro.scenario7.desc': 'Recipe recommendations, travel planning, schedule reminders, health management - organize your life.',
            'intro.scenario8.title': '8. Enterprise Collaboration 👥',
            'intro.scenario8.desc': 'Feishu/Telegram bots, team knowledge bases, meeting notes, project management.',
            'intro.scenario9.title': '9. Research & Investigation 🔬',
            'intro.scenario9.desc': 'Literature reviews, competitive analysis, market research, information aggregation - gain insights quickly.',
            'intro.scenario10.title': '10. Creative Entertainment 🎨',
            'intro.scenario10.desc': 'Story writing, game design, roleplay, fun conversations - unleash your creativity.',
            'intro.architecture': '🏗️ Technical Architecture Overview',
            'intro.architecture.desc': 'OpenClaw uses a modular architecture design with the following core components:',
            'intro.arch.gateway': 'Gateway',
            'intro.arch.gateway.desc': 'HTTP server handling all requests and session management',
            'intro.arch.agent': 'Agent Runtime',
            'intro.arch.agent.desc': 'AI model invocation and tool execution engine',
            'intro.arch.skill': 'Skill System',
            'intro.arch.skill.desc': 'Pluggable skill extension mechanism',
            'intro.arch.memory': 'Memory Layer',
            'intro.arch.memory.desc': 'Long-term memory and context management',
            'intro.arch.channel': 'Channel Adapters',
            'intro.arch.channel.desc': 'Multi-channel integration adapters (Feishu, Telegram, etc.)',
            'intro.arch.cron': 'Cron Scheduler',
            'intro.arch.cron.desc': 'Scheduled task scheduler',
            'intro.community': '🎉 Community Ecosystem',
            'intro.community.desc': 'OpenClaw has an active developer community continuously contributing skills, plugins, and improvements:',
            'intro.community.skills': '🌟 100+ Community Skills',
            'intro.community.skills.desc': 'From web crawlers to database management, everything you need',
            'intro.community.channels': '📦 30+ Integration Channels',
            'intro.community.channels.desc': 'Support for mainstream communication tools and platforms',
            'intro.community.updates': '🔥 Weekly Updates',
            'intro.community.updates.desc': 'Rapid iteration, continuous optimization',
            'intro.community.languages': '🌍 Multi-language Support',
            'intro.community.languages.desc': 'Chinese, English, Japanese, and more',
            'intro.community.opensource': '🤝 Open Source Collaboration',
            'intro.community.opensource.desc': 'Active Issues and PR discussions on GitHub',
            'intro.ready': '🚀 Ready to Get Started?',
            'intro.ready.desc': 'Continue reading the Installation & Configuration section below, or join our Discord community for help!',
            
            // Install page detailed content
            'install.step1': 'Step 1: Install Node.js',
            'install.step2': 'Step 2: Install OpenClaw',
            'install.step3': 'Step 3: Run Wizard',
            'install.step4': 'Step 4: Start Chatting',
            'install.step5': 'Step 5',
            'install.nodejs': 'Install Node.js',
            'install.nodejs.desc': 'Visit nodejs.org to download and install v22+.',
            'install.openclaw': 'Install OpenClaw',
            'install.wizard': 'Run Wizard',
            'install.wizard.desc': 'Follow prompts to select AI model (recommend Kimi or DeepSeek) and complete configuration.',
            'install.startChat': 'Start Chatting',
            'install.startChat.desc': 'Or open browser and visit http://localhost:18789',
            'install.complete': '✅ Done! You now have an AI assistant running on your own device.', 
            'install.prerequisites': 'Prerequisites',
            'install.prerequisites.warning': '⚠️ Please ensure all requirements are met before installation:',
            'install.os': 'Operating System',
            'install.os.desc': 'Windows 10+ / macOS 11+ / Linux (Ubuntu 20.04+)',
            'install.node': 'Node.js',
            'install.node.desc': '≥ 22.0.0 (Required)',
            'install.npm': 'npm',
            'install.npm.desc': '≥ 10.0.0 (Installed with Node.js)',
            'install.git': 'Git',
            'install.git.desc': 'For version control and skill management',
            'install.memory': 'Memory',
            'install.memory.desc': 'At least 2GB available',
            'install.memory.check': 'Check in Task Manager',
            'install.disk': 'Disk Space',
            'install.disk.desc': 'At least 500MB available',
            'install.network': 'Network',
            'install.network.desc': 'Need access to AI model APIs (may require proxy)',
            'install.network.check': 'Ensure internet access',
            'install.requirement': 'Requirement',
            'install.details': 'Details',
            'install.verifyCmd': 'Verify Command',
            'install.cloudModels': 'Cloud Models',
            'install.localModels': 'Local Models',
            'install.configFormat': 'Configuration File Format',
            'install.deepseek': 'DeepSeek Configuration',
            'install.deepseek.key': 'Get API Key',
            'install.kimi': 'Kimi (Moonshot) Configuration',
            'install.qwen': 'Tongyi Qianwen (Qwen) Configuration',
            'install.ollama': 'Ollama + Qwen Configuration',
            'install.otherLocal': 'Other Local Models',
            
            // Installation steps detailed content
            'install.step1.title': 'Step 1: Install Node.js',
            'install.step1.windows': 'Windows: Visit nodejs.org to download .msi installer',
            'install.step1.macos': 'macOS:',
            'install.step1.linux': 'Linux:',
            'install.step2.title': 'Step 2: Install OpenClaw Globally',
            'install.step3.title': 'Step 3: Verify Installation',
            'install.step3.desc': 'Should output version number, e.g.: 2026.3.24',
            'install.source.step1': 'Step 1: Clone Repository',
            'install.source.step2': 'Step 2: Install Dependencies and Link',
            'install.docker.step1': 'Step 1: Pull Image',
            'install.docker.step2': 'Step 2: Run Container',
            'install.wizard.title': 'Run Interactive Wizard',
            'install.wizard.desc2': 'The interactive wizard will guide you through the following configurations:',
            'install.wizard.provider': 'Select AI Model Provider',
            'install.wizard.provider.desc': 'Kimi, DeepSeek, Tongyi Qianwen, Ollama, etc.',
            'install.wizard.auth': 'Configure Authentication',
            'install.wizard.auth.desc': 'API key or OAuth authorization',
            'install.wizard.workspace': 'Set Workspace Directory',
            'install.wizard.workspace.desc': 'Default: ~/.openclaw/workspace',
            'install.wizard.channels': 'Configure Channels',
            'install.wizard.channels.desc': 'Feishu, Telegram, WhatsApp, etc. (optional)',
            'install.wizard.daemon': 'Install Daemon',
            'install.wizard.daemon.desc': 'Auto-start on boot (optional)',
            'install.wizard.configLocation': 'Configuration File Location',
            'install.wizard.configLocation.win': 'Windows',
            'install.wizard.configLocation.unix': 'macOS/Linux',
            
            // AI Model Configuration
            'config.ai.title': '🤖 AI Model Configuration',
            'config.ai.cloud': 'Cloud Models',
            'config.ai.cloud.desc': 'Cloud models require no local GPU, called via API, suitable for most users',
            'config.ai.local': 'Local Models',
            'config.ai.local.desc': 'Local models require GPU (8GB+ VRAM recommended), data stays local, suitable for privacy-sensitive scenarios',
            'config.ai.configFormat': 'Configuration File Format',
            'config.ai.configFormat.desc': 'OpenClaw supports multiple configuration file formats, choose based on your needs',
            
            // Model configuration details
            'model.deepseek.title': 'DeepSeek Configuration',
            'model.deepseek.getKey': 'Get API Key',
            'model.deepseek.visit': 'Visit',
            'model.kimi.title': 'Kimi (Moonshot) Configuration',
            'model.kimi.getKey': 'Get API Key',
            'model.qwen.title': 'Tongyi Qianwen (Qwen) Configuration',
            'model.qwen.getKey': 'Get API Key',
            'model.qwen.oauth': 'Tongyi Qianwen supports OAuth login, run',
            'model.qwen.oauth.cmd': 'to authorize',
            
            // Ollama configuration
            'model.ollama.install': '1. Install Ollama',
            'model.ollama.pull': '2. Pull Model',
            'model.ollama.qwen7b': 'Qwen2.5 7B (requires ~4GB VRAM)',
            'model.ollama.qwen14b': 'Qwen2.5 14B (requires ~8GB VRAM)',
            'model.ollama.list': 'List downloaded models',
            'model.ollama.verify': '3. Verify Ollama Running',
            'model.ollama.config': '4. OpenClaw Configuration',
            'model.ollama.start': '5. Start and Test',
            
            // Other local models
            'model.other.llama': 'Llama 3.2',
            'model.other.mistral': 'Mistral',
            'model.other.phi': 'Phi-3',
            
            // Configuration files
            'config.file.main': 'openclaw.json (Main Config File)',
            'config.file.main.desc': 'This is the main configuration file for OpenClaw, located at',
            'config.file.auth': '🔐 auth-profiles.json (Auth Config)',
            'config.file.auth.desc': 'Centralized management of all API keys and authentication info:',
            'config.file.yaml': '⚙️ config.yaml (Optional Format)',
            'config.file.yaml.desc': 'Some scenarios support YAML format configuration:',
            'config.file.env': '.env (Environment Variables)',
            'config.file.env.desc': 'Used to store sensitive information like API keys, not committed to version control',
            'config.file.env.warning': 'Security Reminder:',
            'config.file.env.warning.desc': 'Do not commit .env files to Git repositories!',
            'config.file.agents': 'AGENTS.md (Agent Configuration)',
            'config.file.agents.desc': 'Defines AI agent behavior, roles, and system prompts',
            
            // Installation wizard steps
            'install.wizard.step1': 'Set AI Model Provider',
            'install.wizard.step1.desc': 'Choose Kimi, DeepSeek, Tongyi Qianwen, etc.',
            'install.wizard.step2': 'Configure API Key',
            'install.wizard.step2.desc': 'Enter the key obtained from the model provider',
            'install.wizard.step3': 'Set Workspace Directory',
            'install.wizard.step3.desc': 'Default: ~/.openclaw/workspace',
            'install.wizard.step4': 'Configure Channels',
            'install.wizard.step4.desc': 'Feishu, Telegram, WhatsApp, etc. (optional)',
            'install.wizard.step5': 'Install Daemon',
            'install.wizard.step5.desc': 'Auto-start on boot (optional)',
            'install.wizard.tip': 'Tip:',
            'install.wizard.tip.desc': 'Configuration files will be generated in ~/.openclaw/ directory after completion',
            'install.verify.step1': 'Step 1: Start Gateway',
            'install.verify.expected': 'Expected Output:',
            'install.verify.step2': 'Step 2: Check Status',
            'install.verify.normal': 'Normal Output Example:',
            'install.verify.step3': 'Step 3: Health Check',
            'install.verify.healthResponse': 'Health Check Response Example:',
            'install.verify.step4': 'Step 4: Test Chat',
            'install.verify.webui': 'Or use Web Interface:',
            'install.verify.step5': 'Step 5: View Logs (Troubleshooting)',
            
            // Comparison table
            'compare.privacy': 'Data Privacy',
            'compare.privacy.local': '✅ Fully Local',
            'compare.privacy.cloud': '❌ Cloud Storage',
            'compare.models': 'Model Selection',
            'compare.models.multi': '✅ 30+ Models',
            'compare.models.single': '⚠️ Single Vendor',
            'compare.fileAccess': 'File Access',
            'compare.fileAccess.direct': '✅ Direct Read/Write',
            'compare.fileAccess.upload': '❌ Manual Upload Required',
            'compare.localDeploy': 'Local Deployment',
            'compare.localDeploy.support': '✅ Ollama Supported',
            'compare.localDeploy.nosupport': '❌ Not Supported',
            'compare.cron': 'Scheduled Tasks',
            'compare.cron.builtin': '✅ Built-in Cron',
            'compare.cron.none': '❌ Not Supported',
            'compare.memory': 'Memory System',
            'compare.memory.longterm': '✅ Long-term Memory',
            'compare.memory.session': '⚠️ Session Only',
            'compare.opensource': 'Open Source',
            'compare.opensource.yes': '✅ Fully Open Source',
            'compare.opensource.no': '❌ Closed Source',
            'compare.customSkills': 'Custom Skills',
            'compare.customSkills.yes': '✅ Supported',
            'compare.customSkills.no': '❌ Not Supported',
            'compare.cost': 'Cost',
            'compare.cost.free': '💰 Free + API Fees',
            'compare.cost.subscription': '💰💰 Subscription',
            
            // Platform names
            'platform.windows': 'Windows',
            'platform.macos': 'macOS',
            'platform.linux': 'Linux',
            
            // Error messages
            'error.generic': 'An error occurred',
            'error.notFound': 'Not found',
            'error.invalidInput': 'Invalid input',
            'error.network': 'Network error',
            'error.timeout': 'Request timeout',
            'error.unauthorized': 'Unauthorized',
            'error.forbidden': 'Forbidden',
            'error.server': 'Server error',
            'error.unknown': 'Unknown error',
            'error.config': 'Configuration error',
            'error.fileNotFound': 'File not found',
            'error.permissionDenied': 'Permission denied',
            'error.diskFull': 'Disk space insufficient',
            'error.alreadyExists': 'Already exists',
            'error.notSupported': 'Operation not supported',
            
            // Messages
            'msg.welcome': 'Welcome to OpenClaw!',
            'msg.setupComplete': 'Setup complete!',
            'msg.configSaved': 'Configuration saved',
            'msg.changesSaved': 'Changes saved',
            'msg.fileSaved': 'File saved',
            'msg.fileDeleted': 'File deleted',
            'msg.skillInstalled': 'Skill installed',
            'msg.skillUpdated': 'Skill updated',
            'msg.skillRemoved': 'Skill removed',
            'msg.channelConnected': 'Channel connected',
            'msg.channelDisconnected': 'Channel disconnected',
            'msg.modelChanged': 'Model switched',
            'msg.languageChanged': 'Language changed',
            'msg.themeChanged': 'Theme changed',
            'msg.noResults': 'No results',
            'msg.loading': 'Loading...',
            'msg.pleaseWait': 'Please wait...',
            'msg.comingSoon': 'Coming soon',
            'msg.workInProgress': 'Work in progress...',
            
            // AI Model related
            'model.provider': 'Model Provider',
            'model.name': 'Model Name',
            'model.version': 'Model Version',
            'model.type': 'Model Type',
            'model.cloud': 'Cloud Model',
            'model.local': 'Local Model',
            'model.apiKey': 'API Key',
            'model.baseUrl': 'Base URL',
            'model.temperature': 'Temperature',
            'model.maxTokens': 'Max Tokens',
            'model.timeout': 'Timeout',
            'model.retry': 'Retry Count',
            'model.fallback': 'Fallback Model',
            
            // Model provider names
            'model.openai': 'OpenAI',
            'model.anthropic': 'Anthropic',
            'model.google': 'Google',
            'model.moonshot': 'Moonshot (Kimi)',
            'model.deepseek': 'DeepSeek',
            'model.alibaba': 'Alibaba (Qwen)',
            'model.ollama': 'Ollama',
            'model.siliconflow': 'SiliconFlow',
            
            // Configuration related
            'config.file': 'Config File',
            'config.path': 'Config Path',
            'config.edit': 'Edit Config',
            'config.reset': 'Reset Config',
            'config.backup': 'Backup Config',
            'config.restore': 'Restore Config',
            'config.import': 'Import Config',
            'config.export': 'Export Config',
            'config.validate': 'Validate Config',
            'config.reload': 'Reload Config',
            
            // Skills related
            'skill.name': 'Skill Name',
            'skill.description': 'Skill Description',
            'skill.version': 'Version',
            'skill.author': 'Author',
            'skill.license': 'License',
            'skill.repository': 'Repository',
            'skill.documentation': 'Documentation',
            'skill.install': 'Install Skill',
            'skill.uninstall': 'Uninstall Skill',
            'skill.update': 'Update Skill',
            'skill.enable': 'Enable Skill',
            'skill.disable': 'Disable Skill',
            'skill.configure': 'Configure Skill',
            'skill.market': 'Skills Marketplace',
            'skill.installed': 'Installed Skills',
            'skill.available': 'Available Skills',
            'skill.popular': 'Popular Skills',
            'skill.new': 'New Skills',
            'skill.search': 'Search Skills',
            'skill.category': 'Skill Category',
            
            // Channel related
            'channel.name': 'Channel Name',
            'channel.type': 'Channel Type',
            'channel.status': 'Channel Status',
            'channel.configure': 'Configure Channel',
            'channel.enable': 'Enable Channel',
            'channel.disable': 'Disable Channel',
            'channel.test': 'Test Channel',
            'channel.webchat': 'Web Chat',
            'channel.telegram': 'Telegram',
            'channel.discord': 'Discord',
            'channel.feishu': 'Feishu',
            'channel.whatsapp': 'WhatsApp',
            'channel.slack': 'Slack',
            'channel.wechat': 'WeChat',
            
            // Feishu page detailed content
            'feishu.pairing': '🔗 Pairing Process (Optional)',
            'feishu.pairing.desc': 'For deep integration between Feishu and OpenClaw, use the pairing feature:',
            
            // Skills page detailed content
            'skills.fileManager.desc': 'Let AI assistant read, write, organize, and search your files.',
            'skills.fileManager.features': 'Features:',
            'skills.fileManager.useCases': 'Use Cases:',
            'skills.webBrowse.desc': 'Let AI assistant access web pages, search information, and scrape content.',
            'skills.calendar.desc': 'Connect your calendar and email for intelligent schedule management and email processing.',
            'skills.custom.desc': 'Create your own skills to meet specific needs.',
            
            // Uninstall page detailed content
            'uninstall.interactive': 'Interactive Uninstall',
            'uninstall.auto': 'Automatic Uninstall',
            'uninstall.windows': 'Windows',
            'uninstall.macos': 'macOS',
            'uninstall.linux': 'Linux',
            
            // Common commands and status
            'cmd.install': 'Install',
            'cmd.install.global': 'Global Install',
            'cmd.uninstall': 'Uninstall',
            'cmd.update': 'Update',
            'cmd.start': 'Start',
            'cmd.stop': 'Stop',
            'cmd.restart': 'Restart',
            'cmd.status': 'Check Status',
            'cmd.config': 'Configure',
            'cmd.chat': 'Chat',
            'cmd.help': 'Help',
            'cmd.version': 'Version',
            
            // Status messages
            'status.success': 'Success',
            'status.error': 'Error',
            'status.warning': 'Warning',
            'status.info': 'Info',
            'status.loading': 'Loading...',
            'status.done': 'Done',
            'status.pending': 'Pending',
            
            // Action buttons
            'action.confirm': 'Confirm',
            'action.cancel': 'Cancel',
            'action.save': 'Save',
            'action.delete': 'Delete',
            'action.edit': 'Edit',
            'action.add': 'Add',
            'action.remove': 'Remove',
            'action.search': 'Search',
            'action.filter': 'Filter',
            'action.refresh': 'Refresh',
            'action.download': 'Download',
            'action.upload': 'Upload',
            'action.share': 'Share',
            'action.copy': 'Copy',
            'action.paste': 'Paste',
            'action.cut': 'Cut',
            'action.selectAll': 'Select All',
            'action.undo': 'Undo',
            'action.redo': 'Redo',
            
            // Form labels
            'form.name': 'Name',
            'form.description': 'Description',
            'form.email': 'Email',
            'form.password': 'Password',
            'form.confirmPassword': 'Confirm Password',
            'form.url': 'URL',
            'form.token': 'Token',
            'form.key': 'Key',
            'form.value': 'Value',
            'form.type': 'Type',
            'form.category': 'Category',
            'form.tag': 'Tag',
            'form.status': 'Status',
            'form.required': 'Required',
            'form.optional': 'Optional',
            'form.default': 'Default',
            'form.custom': 'Custom',
            
            // Time related
            'time.now': 'Now',
            'time.today': 'Today',
            'time.yesterday': 'Yesterday',
            'time.tomorrow': 'Tomorrow',
            'time.thisWeek': 'This Week',
            'time.lastWeek': 'Last Week',
            'time.thisMonth': 'This Month',
            'time.lastMonth': 'Last Month',
            'time.recent': 'Recent',
            'time.justNow': 'Just now',
            'time.minutesAgo': 'minutes ago',
            'time.hoursAgo': 'hours ago',
            'time.daysAgo': 'days ago',
            
            // File related
            'file.name': 'File Name',
            'file.size': 'Size',
            'file.type': 'Type',
            'file.path': 'Path',
            'file.folder': 'Folder',
            'file.document': 'Document',
            'file.image': 'Image',
            'file.video': 'Video',
            'file.audio': 'Audio',
            'file.archive': 'Archive',
            'file.code': 'Code File',
            'file.new': 'New File',
            'file.open': 'Open File',
            'file.save': 'Save File',
            'file.saveAs': 'Save As',
            'file.rename': 'Rename',
            'file.delete': 'Delete File',
            'file.move': 'Move',
            'file.copy': 'Copy',
            'file.duplicate': 'Duplicate',
            
            // Resources page detailed content
            'resources.docs': 'Official Documentation',
            'resources.docs.desc': 'Complete user guide',
            'resources.github': 'GitHub Repository',
            'resources.github.desc': 'Source code and issue tracking',
            'resources.clawhub': 'Skills Marketplace',
            'resources.clawhub.desc': 'Discover and share skills',
            'resources.releases': 'Changelog',
            'resources.releases.desc': 'Version update history',
            'resources.discord': 'Discord Community',
            'resources.discord.desc': 'Real-time chat and Q&A',
            'resources.telegram': 'Telegram Group',
            'resources.telegram.desc': 'Chinese discussions',
            'resources.twitter': 'Twitter/X',
            'resources.twitter.desc': 'Official updates',
            'resources.gettingStarted': 'Getting Started Guide',
            'resources.gettingStarted.desc': 'Using OpenClaw from scratch',
            'resources.skillDev': 'Skill Development Tutorial',
            'resources.skillDev.desc': 'Create custom skills',
            'resources.feishuGuide': 'Feishu Integration Guide',
            'resources.feishuGuide.desc': 'Advanced configuration guide',
            'resources.automation': 'Automation Workflows',
            'resources.automation.desc': 'Scheduled tasks and automation',
            'resources.bugReport': 'Report Bug',
            'resources.featureRequest': 'Feature Request',
            'resources.submitSkill': 'Submit Skill',
            'resources.sponsor': 'Sponsor Project',
            
            // About page additional translations
            'about.team.title': 'About OpenClaw',
            'about.tagline': 'Open Source · Local First · Privacy First',
            'about.mission': '🚀 Our Mission',
            'about.mission.text': 'OpenClaw is an open-source AI assistant framework project, born in 2024. Our goal is simple: let everyone run AI assistants on their own devices, without relying on cloud services, protecting personal privacy.',
            'about.why': '💡 Why Create OpenClaw?',
            'about.why.text': 'We believe AI should be a tool for everyone, not just a few companies. Through open source and local execution, we give users complete control over their data and AI experience.',
            'about.values.core': 'Core Values',
            'about.values.privacy': '🔒 Privacy First - Data is stored locally, not uploaded to our servers',
            'about.values.opensource': '🌍 Open Source - Code is fully open source, subject to community oversight',
            'about.values.community': '🤝 Community Driven - Maintained and developed by global contributors',
            'about.values.free': '💰 Free to Use - Software is free, only pay for AI model API usage',
            'about.values.customizable': '🔧 Highly Customizable - Supports custom skills, multi-channel integration',
            'about.history.title': '📅 Project History',
            'about.history.2024q1': 'Early 2024',
            'about.history.2024q1.title': 'Project Born',
            'about.history.2024q1.desc': 'OpenClaw project was first released on GitHub, aiming to create a locally-run AI assistant framework.',
            'about.history.2024q2': 'Mid 2024',
            'about.history.2024q2.title': 'Core Features Complete',
            'about.history.2024q2.desc': 'Support for multiple models (Kimi, DeepSeek, Qwen, etc.), with core features like file access, web browsing, and scheduled tasks.',
            'about.history.2024q4': 'Late 2024',
            'about.history.2024q4.title': 'Channel Integration',
            'about.history.2024q4.desc': 'Integration with Feishu, Telegram, WhatsApp, Discord and other platforms, allowing AI assistant to respond anytime, anywhere.',
            'about.history.2025': '2025',
            'about.history.2025.title': 'Skill Ecosystem',
            'about.history.2025.desc': 'Launch of ClawHub skills marketplace, where community contributors can create and share custom skills to extend AI assistant capabilities.',
            'about.history.2026': '2026',
            'about.history.2026.title': 'Continuous Evolution',
            'about.history.2026.desc': 'Performance optimization, improved user experience, expanded device control features (phone/tablet connection), and growing user base.',
            'about.team.section': '👥 Our Team',
            'about.team.desc': 'OpenClaw is maintained by a group of developers passionate about open source and AI technology. We are distributed around the world, collaborating via the internet, dedicated to building a better AI assistant framework.',
            'about.team.core': 'OpenClaw Core',
            'about.team.core.role': 'Core Development Team',
            'about.team.core.bio': 'Responsible for core framework development, architecture design, and version releases',
            'about.team.contributors': 'Community Contributors',
            'about.team.contributors.role': 'Global Developers',
            'about.team.contributors.bio': 'Volunteers from around the world contributing code, documentation, and translations',
            'about.team.skillCreators': 'Skill Creators',
            'about.team.skillCreators.role': 'Skill Developers',
            'about.team.skillCreators.bio': 'Creating and sharing custom skills to enrich the OpenClaw ecosystem',
            'about.team.admins': 'Community Admins',
            'about.team.admins.role': 'Community Operations',
            'about.team.admins.bio': 'Maintaining Discord, Telegram and other communities, answering user questions',
            'about.join.title': '🤝 Join Us!',
            'about.join.desc': 'Whether you are a developer, documentation writer, translation volunteer, or regular user, you can contribute in the following ways:',
            'about.join.code': 'Submit code or bug fixes',
            'about.join.docs': 'Improve documentation and tutorials',
            'about.join.skills': 'Create custom skills',
            'about.join.help': 'Help other users solve problems',
            'about.join.share': 'Share usage experiences and case studies',
            'about.values.title': '💎 Our Values',
            'about.values.opensource.title': 'Open Source Spirit',
            'about.values.opensource.desc': 'Believe in the power of open collaboration, transparent code, subject to oversight',
            'about.values.privacy.title': 'Privacy Protection',
            'about.values.privacy.desc': 'User data belongs to users, stored locally, not actively collected',
            'about.values.userfirst.title': 'User First',
            'about.values.userfirst.desc': 'Listen to user feedback, continuously improve product experience',
            'about.values.innovation.title': 'Continuous Innovation',
            'about.values.innovation.desc': 'Explore more possibilities for AI assistants, constantly pushing boundaries',
            'about.stats.title': '📊 Project Statistics',
            'about.stats.desc': 'Thanks to support from users worldwide, OpenClaw is continuously growing:',
            'about.stats.models': 'Supported AI Models',
            'about.stats.stars': 'GitHub Stars',
            'about.stats.skills': 'Community Skills',
            'about.stats.contributors': 'Contributors',
            'about.stats.growth': '📈 Continuous Growth',
            'about.stats.growth.desc': 'Above data is for reference only, please visit GitHub repository for latest statistics',
            'about.partners.title': '🤝 Partners',
            'about.partners.desc': 'OpenClaw integrates with multiple excellent AI models and services, thanks to their API support:',
            'about.partners.moonshot': 'Moonshot (Kimi) - AI model with excellent long text processing capabilities',
            'about.partners.deepseek': 'DeepSeek - High-performance, low-cost AI model service',
            'about.partners.qwen': 'Tongyi Qianwen - Multimodal AI model from Alibaba DAMO Academy',
            'about.partners.ollama': 'Ollama - Open source tool for running large models locally',
            'about.partners.feishu': 'Feishu - Enterprise collaboration platform providing bot integration',
            'about.contact.title': '📬 Contact Us',
            'about.contact.desc': 'For any questions, suggestions, or partnership inquiries, please contact us through the following channels:',
            'about.contact.heading': '👋 Get in Touch',
            'about.contact.subtitle': 'We are happy to hear from you, whether it is feedback, feature suggestions, or partnership discussions'
        }
    };

    // 获取当前语言
    function getCurrentLang() {
        const stored = localStorage.getItem(I18N_CONFIG.storageKey);
        if (stored && I18N_CONFIG.supportedLangs.includes(stored)) {
            return stored;
        }
        // 检测浏览器语言
        const browserLang = navigator.language || navigator.userLanguage;
        if (browserLang && browserLang.startsWith('zh')) {
            return 'zh';
        }
        return I18N_CONFIG.defaultLang;
    }

    // 设置语言
    function setLang(lang) {
        if (!I18N_CONFIG.supportedLangs.includes(lang)) {
            lang = I18N_CONFIG.defaultLang;
        }
        localStorage.setItem(I18N_CONFIG.storageKey, lang);
        document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
        applyTranslations();
        updateLangSwitcher();
    }

    // 获取翻译
    function t(key) {
        const lang = getCurrentLang();
        return translations[lang][key] || translations[I18N_CONFIG.defaultLang][key] || key;
    }

    // 应用翻译
    function applyTranslations() {
        const lang = getCurrentLang();
        
        // 翻译带有 data-i18n 属性的元素
        document.querySelectorAll('[data-i18n]').forEach(el => {
            const key = el.getAttribute('data-i18n');
            const text = translations[lang][key] || translations[I18N_CONFIG.defaultLang][key];
            if (text) {
                if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                    el.placeholder = text;
                } else if (el.tagName === 'IMG') {
                    el.alt = text;
                } else {
                    el.textContent = text;
                }
            }
        });

        // 翻译带有 data-i18n-html 属性的元素（保留 HTML）
        document.querySelectorAll('[data-i18n-html]').forEach(el => {
            const key = el.getAttribute('data-i18n-html');
            const text = translations[lang][key] || translations[I18N_CONFIG.defaultLang][key];
            if (text) {
                el.innerHTML = text;
            }
        });

        // 翻译页面标题
        const pageName = document.body.getAttribute('data-page');
        if (pageName && translations[lang]['title.' + pageName]) {
            document.title = translations[lang]['title.' + pageName];
        }

        // 触发自定义事件
        document.dispatchEvent(new CustomEvent('i18n:changed', { detail: { lang } }));
    }

    // 更新语言切换器状态
    function updateLangSwitcher() {
        const lang = getCurrentLang();
        document.querySelectorAll('.lang-btn').forEach(btn => {
            btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
        });
    }

    // 创建语言切换器
    function createLangSwitcher() {
        const existing = document.querySelector('.lang-switcher');
        if (existing) return;

        const switcher = document.createElement('div');
        switcher.className = 'lang-switcher';
        switcher.innerHTML = `
            <button class="lang-btn ${getCurrentLang() === 'zh' ? 'active' : ''}" data-lang="zh" title="中文">中</button>
            <button class="lang-btn ${getCurrentLang() === 'en' ? 'active' : ''}" data-lang="en" title="English">EN</button>
        `;

        switcher.addEventListener('click', (e) => {
            if (e.target.classList.contains('lang-btn')) {
                const lang = e.target.getAttribute('data-lang');
                setLang(lang);
            }
        });

        return switcher;
    }

    // 初始化
    function init() {
        // 设置初始语言
        const lang = getCurrentLang();
        document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';

        // 应用翻译
        applyTranslations();

        // 添加语言切换器到页面
        const switcher = createLangSwitcher();
        if (switcher) {
            // 插入到主题切换按钮旁边或页面顶部
            const themeToggle = document.querySelector('.theme-toggle');
            if (themeToggle && themeToggle.parentNode) {
                themeToggle.parentNode.insertBefore(switcher, themeToggle.nextSibling);
            } else {
                document.body.insertBefore(switcher, document.body.firstChild);
            }
        }

        // 监听语言切换
        updateLangSwitcher();
    }

    // DOM 加载完成后初始化
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

    // 暴露全局 API
    window.I18N = {
        t: t,
        setLang: setLang,
        getLang: getCurrentLang,
        apply: applyTranslations,
        config: I18N_CONFIG
    };
})();
